spring:
  application:
    name: multi-tenant-platform

  # MySQL Connection - USE ENVIRONMENT VARIABLES
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/saas_master?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:Ankur265}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA Settings
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true

  # Flyway Migration
  flyway:
    enabled: false
   # baseline-on-migrate: true
    #locations: classpath:db/migration

# Server Configuration
server:
  port: ${SERVER_PORT:8080}

# Logging
logging:
  level:
    root: INFO
    com.saas.platform: ${LOG_LEVEL:DEBUG}
    org.springframework.security: ${SECURITY_LOG_LEVEL:DEBUG}

# JWT Configuration - USE ENVIRONMENT VARIABLES
app:
  jwt:
    secret: ${JWT_SECRET:my-super-secret-key-for-jwt-token-generation-must-be-at-least-256-bits-long-for-security}
    expiration: ${JWT_EXPIRATION:86400000}